server:
  port: 7002
springdoc:
  swagger-ui:
    enabled: true
    operations-sorter: method
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


token:
  secret-key: "SECRET"
  refresh-key: "REFRESH_SECRET"
  token-time-for-minutes: 300
  refresh-time-for-minutes: 300